### ISSUE TITLE
Eclipse 2022-12 does not recognise '.classpath' format after M2E Maven import

### ISSUE THREAD

**Issue by m4urer** [eclipse-aspectj/aspectj#223]
The methods are not weaved/the eclipse 2022-12 (and aspect markers do not show) with an aspectj configured project because the .classpath that a maven project generates for src/main/java is now
```
<classpathentry kind="src" output="target/classes" path="src/main/java">
	<attributes>
		<attribute name="optional" value="true"/>
		<attribute name="maven.pomderived" value="true"/>
	</attributes>
</classpathentry>
```
instead of 
```
<classpathentry kind="src" output="target/classes" path="src/main/java"/>
```
I have multiple projects using aspectj, and none of them work in the latest eclipse (the aspects are not weaved) **unless I manually change the .classpath from the new format to the old one**. And every time I update the project from maven, the .classpath is once again changed and the aspects don't work.

The only thing I need to do for it to work is change the .classpath src/main/java entry to
`<classpathentry kind="src" output="target/classes" path="src/main/java"/> `
(remove the attributes) and everything works. 
But I can't find a way to avoid the classpath to use that structure so it's very difficult to work like this. 

You can test it with this project
[spring-aop-2](https://github.com/eugenp/tutorials/tree/188201d3247ee57704c3d8b37aa43a9f3147b694/spring-aop-2)
and the same happens.  the aspects are not marked in eclipse unless I manually change the classpath.

Could you please help?
Thanks!

**Comment by kriegaex** [comment]
Thanks for your inquiry.

_**Off-topic situation report:** I actually next to never use AJDT, especially not in combination with Maven. My main IDE is IntelliJ IDEA, even for working on AspectJ itself. When AspectJ Core is understaffed, this is true even more so for AJDT which does not have any active maintainer. I managed to somehow keep it alive, but several things are broken. This one looks severe enough to look into, but I am quite busy with my job Mon-Fri and a few things I am improving in AspectJ on weekends. I am not promising anything about when I can take a look, whether I understand enough to fix it at all and when I might be able to push out a new AJDT version to the corresponding update site._

As soon as there is something testable, I will report back here.

**Comment by kriegaex** [comment]
@m4urer, I just quickly started Eclipse 2022-12 and imported the non-AspectJ project you mentioned. Please note, that Spring AOP is not the same as AspectJ. It works without any problems. Maybe, instead of the _spring-aop-2_ module, you meant to point to the [_spring-aop_](https://github.com/eugenp/tutorials/tree/188201d3247ee57704c3d8b37aa43a9f3147b694/spring-aop) module, which does actually use AspectJ Maven and native AspectJ. For that one, I really do see import problems. The same is true for my local AspectJ Maven projects.

I am not sure if the reason is to be found within AJDT. Maybe it is rather about the [Maven to Eclipse (m2e) connector](https://github.com/eclipse/org.aspectj/blob/master/docs/developer/IDE.md#maven-to-eclipse-m2e-connector) mentioned in the IDE setup guide and which is maintained outside of the AspectJ and AJDT projects. @joker1, what do you think? Can you please take a look and fix the problem in the Maven connector? Somehow, during import the AspectJ nature is not added to the Eclipse project.

**Comment by m4urer** [comment]
Hi @kriegaex , I just made a mistake with the link, it's [spring-aop](https://github.com/eugenp/tutorials/tree/master/spring-aop). There's an **com.baeldung.aspectj** package in that project where you can see the aspect markers are missing (in AccountAspect for example) unless you change the classpath. I noticed the problem in my own projects, just as you did, I just wanted to give a easy/public example just in case it was necessary. I had to add the aspectj nature when I imported the project if I remember correctly, but the .classpath format is still causing the weaving issues.

**Comment by kriegaex** [comment]
I am currently busy with something else, so I did not try to just reimport the latest JDT Core stuff into AJDT and see if somehow it magically fixes the problem, always hoping that not AJDT itself is parsing the _.classpath_ file. It might be an M2E connector issue, a question of just updating JDT Core in AJDT or even something requiring changes in AJDT itself (which would be the worst case for me, not knowing the code base or Eclipse OSGi plugin programming in general).

**Comment by kriegaex** [comment]
Status quo: I just upgraded a few dependencies in AJDT, rebuilt and upgraded AJDT in my local Eclipse 2022-12. It does not help. Here is the corresponding Eclipse error log when importing a multi-module Maven project containing AspectJ Maven Plugin:

```text
!ENTRY org.eclipse.m2e.logback.appender 4 0 2023-02-11 09:18:29.714
!MESSAGE Launch configuration Application (189) references non-existing project application.
!STACK 1
org.eclipse.core.runtime.CoreException: Launch configuration Application (189) references non-existing project application.
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1861)
	at org.eclipse.jdt.launching.JavaRuntime.getJavaProject(JavaRuntime.java:1736)
	at org.eclipse.m2e.jdt.internal.launch.MavenLaunchConfigurationListener.updateLaunchConfiguration(MavenLaunchConfigurationListener.java:64)
	at org.eclipse.m2e.jdt.internal.launch.MavenLaunchConfigurationListener.launchConfigurationChanged(MavenLaunchConfigurationListener.java:50)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.run(LaunchManager.java:225)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.notify(LaunchManager.java:209)
	at org.eclipse.debug.internal.core.LaunchManager.launchConfigurationChanged(LaunchManager.java:2147)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.writeNewFile(LaunchConfigurationWorkingCopy.java:377)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave0(LaunchConfigurationWorkingCopy.java:259)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave(LaunchConfigurationWorkingCopy.java:229)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave(LaunchConfigurationWorkingCopy.java:187)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.enable(MavenRuntimeClasspathProvider.java:399)
	at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.enable(MavenRuntimeClasspathProvider.java:428)
	at org.eclipse.m2e.jdt.internal.launch.MavenLaunchConfigurationListener.mavenProjectChanged(MavenLaunchConfigurationListener.java:132)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:832)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:985)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:315)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:256)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:166)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:139)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob$1.doCreateMavenProjects(ImportMavenProjectsJob.java:70)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:56)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob.runInWorkspace(ImportMavenProjectsJob.java:79)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.jdt.launching 4 107 2023-02-11 09:18:29.714
!MESSAGE Launch configuration Application (189) references non-existing project application.

!ENTRY org.eclipse.m2e.logback.appender 2 0 2023-02-11 09:18:31.963
!MESSAGE CatalogItem org.eclipse.m2e.discovery.lifecyclemapping.m2e-egit does not contain lifecycle mapping metadata
```

@joker1, would you please take a look and tell me if this can be fixed in your project, or if you think it must be fixed in AJDT? I have no clue at all.

During project import there were also warnings about Eclipse not being able to find anything on the Marketplace which maps to AspectJ Maven Plugin.

**Comment by kriegaex** [comment]
@m4urer, because @joker1 has not reacted yet, I upgraded the AJDT M2E Connector to 2022-12, but without really knowing much about what I was doing. It seems to work now, but there are error messages for older AspectJ Maven versions depending on Java 8 _tools.jar_.
* Ideally, you should use `dev.aspectj:aspectj-maven-plugin:1.13.1`. It is capable of accomodating the latest source, target, release versions supported by AspectJ (e.g. Java 19 when used with AspectJ Tools 1.9.19) and in general a bit more feature-rich than the Mojohaus version. (Spoiler: I am the maintainer.)
* The second best choice is `org.codehaus.mojo:aspectj-maven-plugin:1.14.0`.

The new connector version is quite hacky, I might have broken something, even though I did not notice anything yet. It depends on the latest M2E 2.x versions contained in more recent Eclipse versions. I would appreciate some feedback. Please use this preliminary update site:

https://aspectj.dev/eclipse/m2eclipse-ajdt/eclipse-2022-12/

The build is unsigned, just accept that during installation.

**Comment by m4urer** [comment]
Hi @kriegaex , first of all, **THANK YOU SO MUCH** for all your effort!
I'm sorry to report that I've updated the connector, but the .classpath problem persists. Did you tested locally and got it working?

In my projects I'm using JAVA 17 + dev.aspectj 1.13.1 and aspectj 1.9.19.
In the spring-aop project I used as an example, they're using mojo so I've updated to 1.14.0 and kept aspectj 1.9.1, but the error is the same. This project is using java 1.8.

In my eclipse I have JRE 17, which doesn't have tools.jar in the /lib folder anymore (it's embedded, so the jar is not there anymore, I think it's like that since java 11). So what I've noticed with the update, is that the JAVA 1.8 project is now throwing an error since tools.jar is missing (and I guess that's hardcoded in the plugin somehow). So maybe the plugin should be compiled using java 11+ or that part of the code fixed. Could that be causing the issue? 
What I did is update the spring-aop project to java 17, and the tools.jar error was fixed, but the weaving problem it's still there.
But I'm sending the error image just in case is useful somehow
![tools-jar](https://user-images.githubusercontent.com/3002779/218482813-8478ddd5-94ba-4a30-8c00-6082bc6bce5e.png)

Anything else I can try?
Thanks again!

**Comment by kriegaex** [comment]
Like I said, do not use old AspectJ Maven versions. Your project uses AJ Maven 1.11. Use the versions I told you to, please. Your screenshot clearly says that Codehaus version 1.11 is being used. Please upgrade, save the POM and then right-click the module and select "Maven - Update project" (Alt-F5) from the context menu.

**Comment by m4urer** [comment]
I took the screen capture before updating. Like I said, once I updated to
mojo 1.14.0 and java 17 the tools.jar problem disappeared.
But I still need to fix the .classpath manually for eclipse to weave the
classes.
Same for my projects with dev.aspectj

**Comment by kriegaex** [comment]
Hm, actually, before changing the M2E connector, I also built a new local AJDT version. I It did not help, so I did not think it would make a difference. But maybe, it is a combination of AJDT and M2E. Please try my development build of AJDT together with the M2E connector:

https://aspectj.dev/eclipse/ajdt/426/

Sorry for urging you to experiment, but I just did what I could. Actually, I don't "speak Elcipse OSGi plugins", so I am just playing around there. Anyway, locally it works for me.

**Comment by m4urer** [comment]
Same problem. I've updated ajdt and m2eclipse-ajdt as requested, but I still have the same problem. I need to manually fix the .classpath for the weaving to work.
![aspect-installed](https://user-images.githubusercontent.com/3002779/218564625-4c4969cd-3d9f-4f43-b883-a0877e886678.png)
I don't know how it's now fixed for you and not for me. could it be the java version somehow? what are you using? I'm using 17. Could you check you eclipse .classpath file? what's the format for src/main/java entry?

**Comment by kriegaex** [comment]
> I don't know how it's now fixed for you and not for me.

I do not know, either. For me it just works.

> could it be the java version somehow? what are you using? I'm using 17.

Eclipse 2022-12 comes bundled with Java 17, so my M2E importer uses the same. When I first opened the Baeldung Spring sample project with the old AJ Maven version requiring _tools.jar_, I had the same error as you, but after fixing that in the POM, it works fine.

> Could you check you eclipse .classpath file? what's the format for src/main/java entry?

It looks just like yours, e.g.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

My Eclipse installation is from 2019 or so, upgraded again and again using the normal Eclipse update, not reinstalled from scratch. That is the only "anomaly" I can think of. Other than actually looking at your local situation via Teamviewer or so, I currently have no new ideas.

**Comment by m4urer** [comment]
Please try this out. 
Remove aspectj capacity from the aop-project, then add it again. Then I can see the eclipse markers.
![github1](https://user-images.githubusercontent.com/3002779/218816444-ef0eb387-3e95-467e-ac1c-d46b6fbe55f7.png)
But then, I did a **maven->update** project followed by a **project->clean** (i think even without the clean), and the markers are once again lost, and impossible to get back unless I do the .classpath trick or again remove/add the capability.
Could you check if it happens to you too?

**Comment by kriegaex** [comment]
Oh yeah, that is actually true. Before, I simply checked that the AJ nature was imported and the aspects were being applied when compiling in Eclipse, which both is true. I did not focus on the aspect markers. For those, the classpath XML format really needs to be altered manually. So this might need a fix in AJDT on top of the fix in the M2E connector. Maybe, one of these days after work I can look into that.

But in AJDT much more is broken, e.g. there are errors when opening the "Aspect Visualization" view. I have no idea for how long that was broken already (do you?), and I do not feel so inclined to spend my sparetime learning Eclipse plugin development and understand the complex AJDT code. I wish someone who knows how to do that would come along and maintain AJDT, me just giving input concerning AspectJ particulars.

**Comment by m4urer** [comment]
Sorry, I don't know if **aspect visualization** was broken before you compiled the new version.
I'm amazed that I'm the only one with this problem, is nobody using aspectj and maven with eclipse since since the broken version?
For us removing aspectj would be very difficult. Maybe we could consider an IDE switch, but that also have it's learning curve.
Since you said intellij is your main idea, should the same maven project work on intellij? would switching IDEs solve the problem?
Thanks!

**Comment by kriegaex** [comment]
The (still falsely co-called) _spring-aop_ project works nicely with Maven auto-import in IntelliJ. But AspectJ support within the IDE requires the Ultimate Edition, even though probably the Maven build as such would work just fine in the Community Edition.

Unfortunately, AspectJ support in IDEA has not been improved in a long time, merely maintained minimally. E.g., there are no aspect markers like in Eclipse with AJDT. My plea to open-source the AspectJ plugin in order to maybe attract developers to improve it has been ignored several times by JetBrains staff.

I have taken some time earlier today to debug into AJDT, in order to find out how to fix the marker issue, but with my level of knowledge this proves to be just what I expected: searching for a needle in a haystack. If you are lucky, I might find something and figure out a way to solve it, but presently I am still pretty much clueless. JDT Core parses the XML just fine, but somehwere the additional attributes seem to derail AJDT later on anyway, even though AJDT uses attributes for things like inpath and aspectpath, too. Maybe it assumes that there are no other possible attributes, or a relatively new `hashCode` method in JDT Core is the culprit. I shall keep you posted, if there are any good news. I do not feel so inclined to invest much more time, but maybe when I am bored, I look into it again. Probably, a former contributor like @aeisenberg would be able to fix this in no time, but we have to accept that people have moved on from AJDT.

**Comment by kriegaex** [comment]
> Please try my development build of AJDT together with the M2E connector:
> 
> https://aspectj.dev/eclipse/ajdt/426/

Please try again, @m4urer. For me, the markers are OK now. I spent way more time with this during the last weekends. I hope it is working for you now, too.

**Comment by kriegaex** [comment]
For the record: #226 automatically closed this issue. But the local changes fixing it in AJDT have not been pushed and merged yet.

**Comment by kriegaex** [comment]
@m4urer, I found the reason for the errors when opening the "Aspect Visualization" view. I fixed it, please also retest that after updating to the latest AJDT version for 4.26 (2022-12). Looking forward to your feedback.

**Comment by m4urer** [comment]
Hi @kriegaex I can confirm that it looks fixed! I had to update de AJDT version, and then do a maven update and clean on all projects, but it seems to be working. I can also confirm the aspect visualization is working.
I'll start using the upgraded eclipse version probably in the coming weeks so I'll give it a good try, but for now.. this is definitely closed. 
I'm beyond grateful for the work you've put in! Thanks for keeping this alive without any help at all!

**Comment by kriegaex** [comment]
Reopening until there is an AJDT version on an Eclipse update site.

**Comment by kriegaex** [comment]
The new update site https://download.eclipse.org/tools/ajdt/426/dev/update is operational and documented in https://github.com/eclipse/org.aspectj/blob/master/docs/developer/IDE.md#aspectj-development-tools-ajdt.
