### ISSUE TITLE
loadtime weaving seems not to work in eclipse 2400-03

### ISSUE THREAD

**Issue by urferr** [eclipse-aspectj/aspectj#301]
We use an aspectj plugin to weave some classes in the eclipse IDE. This was working fine until eclipse 2023-12 but now with eclipse 2024-03 its failing. I have also installed the latest version of AJDT but this did not solve the problem. For all the classes there exists an aspect for we get now the following error:

eclipse.buildId=4.31.0.I20240229-0520
java.version=21.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_CH
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.buildship.core
Error
Tue Apr 02 10:59:34 CEST 2024
Project import failed due to an unexpected error.

java.lang.NoClassDefFoundError: org/eclipse/core/internal/resources/ProjectDescription$AjcClosure1
	at org.eclipse.core.internal.resources.ProjectDescription.setNatureIds(ProjectDescription.java:852)
	at org.eclipse.buildship.core.internal.workspace.DefaultWorkspaceOperations.addNature(DefaultWorkspaceOperations.java:219)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.importRootProject(ImportRootProjectOperation.java:105)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation$1.run(ImportRootProjectOperation.java:68)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2468)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.runInWorkspace(ImportRootProjectOperation.java:58)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.run(ImportRootProjectOperation.java:51)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.runInToolingApi(DefaultGradleBuild.java:230)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:197)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:105)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectImportWizardController$5.run(ProjectImportWizardController.java:213)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.internal.resources.ProjectDescription$AjcClosure1 cannot be found by org.eclipse.core.resources_3.20.100.v20240209-1706
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 17 more

For me this looks like classes are not generated by the loadtime weaver.

**Comment by kriegaex** [comment]
Have you changed to the new update site, as described [here](https://github.com/eclipse-aspectj/aspectj/blob/master/docs/developer/IDE.md#eclipse)?

See also:
* https://github.com/eclipse-aspectj/aspectj/issues/297
* https://github.com/eclipse-aspectj/ajdt/issues/49

**Comment by kriegaex** [comment]
Then please, publish a minimal reproducer on GitHub. I cannot debug what I cannot see, compile and run.

**Comment by k-mierzej** [comment]
Hi, I will join your report as I have similar issue. I've described my problem on [stackoverflow](https://stackoverflow.com/questions/78242774/problems-setting-up-product-with-plugins-using-aspectj-on-eclipse-version-2024-0) if you want to see it.

Here is the example Eclipse product which can be build by maven `mvn package` (it needs maven 3.9+ if I remember correctly). During launch of the application, `NoClassDefFoundError` exception is thrown.

[example.zip](https://github.com/eclipse-aspectj/aspectj/files/14848927/example.zip)

**Comment by kriegaex** [comment]
> During launch of the application, `NoClassDefFoundError` exception is thrown.

How do I launch the application? I built the project from the command line successfully. Now, what are the next steps? Warning: I am unexperienced in all things Tycho, Eclipse plugins and OSGi. It might surprise you, but I only use as much of these as is minimally necessary to compile AJDT. I actually have no idea how they work. So please, tell me what to do to reproduce the problem.

**Comment by k-mierzej** [comment]
Sorry, I forgot to specify all the steps required to reproduce the issue.

If maven build is finished, you should have the eclipse application built in following directories:
`./example-ide/target/products/com.example.ide.product/linux/gtk/x86_64/`
`./example-ide/target/products/com.example.ide.product/win32/win32/x86_64/`

**Comment by kriegaex** [comment]
Yeah, I see it. But sorry, how am I supposed to debug this? The application is complex (it seems to be a customised Eclipse IDE or some kind of RCP application of size ~320 MB. I have no idea where to start looking for the root cause of the problem. I also cannot see where and how LTW is used there. Don't you have a small example project which I can simply run from an existing Eclipse 2024-03 IDE installation? It is intransparent to me what is going on under the hood here.

You also seem to use `org.codehaus.mojo:aspectj-maven-plugin:1.15.0`, which by default uses AspectJ 1.9.7 to stay compatible with build environment JDK 8. In your configuration, you do not seem to upgrade the plugin dependency to `aspectjtools` to the current 1.9.22, which is the one containing the JDT Core API changes present in Eclipse 2024-03. Maybe this also influences the outcome, maybe not. BTW, I recommend `dev.aspect:aspectj-maven-plugin:1.14` instead, even though here probably it is not connected to the problem.

**Comment by kriegaex** [comment]
Upgrading the plugin dependency to `aspectjtools:1.9.22` is not helping. I am having trouble to see where AspectJ LTW is used here at all. In the stack trace, I only see Eclipse OSGi stuff, not a single line of AspectJ code is in the stack trace. Furthermore, you seem to be using compile-time weaving, not load-time weaving. Sorry, I am confused. I can only say that I tried a few LTW configurations in Eclipse, and they work fine.

**Comment by kriegaex** [comment]
Note to myself: One possible problem source could be the fact that Eclipse IDE (and with it our dependency JDT Core) is released **before** the support for the next Java version is merged to the main branch, e.g. https://github.com/eclipse-jdt/eclipse.jdt.core/commits/R4_31/ from Feb-17. I.e., AspectJ, being urged by its users to always support the latest Java version but also the latest Eclipse version, always merges later commits, typically right after the new Java beta branch has been merged into the JDT Core main branch. In this case, we merged this version:

```text
$ ajc -version
AspectJ Compiler 1.9.22 - Built: Saturday Mar 23, 2024 at 09:58:15 PDT - Eclipse Compiler b2705b00e91be7 (20Mar2024) - Java22
```

That corresponds to https://github.com/eclipse-jdt/eclipse.jdt.core/commits/b2705b00e91be7 from Mar-20.

I.e., in the meantime classes like `org.eclipse.jdt.internal.compiler.lookup.TypeBinding` might have changed in an incompatible way, which here seems to be the case, e.g. there are now two anonymous inner classes `$1` and `$2` instead of just one in previous versions. Because the relocated classes contained in AspectJ, e.g. `org.aspectj.org.eclipse.jdt.internal.compiler.lookup.TypeBinding`, ought to match the ones in the original JDT core contained in Eclipse IDE, such changes can cause problems.

One possible workaround would be to recommend to users to upgrade their Eclipse installations (or the versions used for building RCP applications or similar) to an Eclipse integration build a close as possible to the merge point, similarly to the recommendations for 2023-12 in https://github.com/eclipse-aspectj/aspectj/blob/master/docs/developer/IDE.md (see the screenshot after the sentence "Your AspectJ-related list of Eclipse update sites could look like this for Eclipse 2023-12").

**Comment by kriegaex** [comment]
@urferr, @k-mierzej If you add https://download.eclipse.org/eclipse/updates/4.32-I-builds/I20240320-0740/ as an update site to your Eclipse IDE or Tyhco build, respectively, does it fix the problem? In Eclipse, you should run IDE updates from that update site and restart the IDE first.

An alternative would be to install Java 22 support from the Eclipse marketplace: https://marketplace.eclipse.org/content/java-22-support-eclipse-2024-03-431. That might also help.

**Comment by k-mierzej** [comment]
@kriegaex, I've used the update site, but that didn't change anything. You've focused on compatibility of versions, but is that even possible, given the fact that the same configuration does work on Linux distro? We have like 20+ jdt and compiler modifications and no problems on linux.

I don't think I am able to provide smaller example, those projects which I've uploaded can be imported to Eclipse IDE but some additional plugins would be needed to run them correctly.

Maybe the reporter will add some additional feedback.

**Comment by kriegaex** [comment]
@k-mierzej, please describe as well as you can how and where you use LTW. Like I said, I see CTW in your build config. Are you using `aspectjweaver.jar` anywhere or some kind of Eclipse weaving support via OSGi? I know that something like that exists, but have no idea how it works and who maintains it. Maybe it needs to be adjusted to recent changes (since 1.21.1, if I remember correctly) in the weaver, where in case of non-woven code `null` is returned instead of the original bytes. Tools accessing the weaver API directly need to adjust their code to that new situation. It is an optimisation which helps to avoid problems in other weaving cases, but which also is a breaking change. Fixing the client code should not be a big deal, but it needs to be done. E.g., I am aware of the fact that the IntelliJ IDEA AspectJ plugin needs to be fixed to accomodate the change. Maybe in case of Eclipse weaving support, the situation is similar. But without being able to reproduce it outside of your huge application, I am afraid I cannot help much. Please tell me everything that might clue me in on the root cause.

**Comment by kriegaex** [comment]
@k-mierzej, I have just remembered the name of the other weaving thingy: [Equinox Weaving](https://eclipse.dev/equinox/weaving/). Maybe whoever maintains that, needs to adjust it to the latest AspectJ changes, if they use weaver classes that otherwise are mostly used by the Aspectj Weaver itself.

**Comment by k-mierzej** [comment]
@kriegaex We do not know each other. I found this issue randomly, and since the original reporter did not provide an example, I decided to speed up the issue resolution by adding mine. I suppose this is a common use case of AspectJ in Eclipse plugin development, which is why they are somewhat similar.

As for debugging it in Eclipse IDE, I believe it may be extremely challenging because when I ran the plugin directly from my IDE instead of the Tycho-built product, it worked fine.

If you want to run my example from another Eclipse IDE, you'll need to import those projects, but first, you'll need to install three additional Eclipse plugins. I think I could prepare the instructions, but it's somewhat pointless if the issue is not reproducible then.
