### ISSUE TITLE
Unsupported class file major version 67

### ISSUE THREAD

**Issue by Dosxx** [eclipse-aspectj/aspectj#317]
```text
java.lang.RuntimeException: The aspect weaver cannot determine any valid method to define auxiliary classes in arbitrary class loaders. Aspect weaving will *not* work, and you will see subsequent errors. Please search for corresponding issues at https://github.com/eclipse-aspectj/aspectj/issues. If there are none, please create a new one.
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.<clinit>(ClassLoaderWeavingAdaptor.java:1043)
	at org.aspectj.weaver.loadtime.Aj.<clinit>(Aj.java:267)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.<clinit>(ClassPreProcessorAgentAdapter.java:27)
	at org.aspectj.weaver.loadtime.Agent.<clinit>(Agent.java:34)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154)
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67
	at aj.org.objectweb.asm.ClassReader.<init>(ClassReader.java:200)
	at aj.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at aj.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at aj.org.objectweb.asm.ClassReader.<init>(ClassReader.java:288)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.getMirrorClassBytes(ClassLoaderWeavingAdaptor.java:1180)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.getMirrorClass(ClassLoaderWeavingAdaptor.java:1166)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.getAccessibleObjectOverrideOffset(ClassLoaderWeavingAdaptor.java:1128)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.createDefineClassMethodHandle(ClassLoaderWeavingAdaptor.java:1100)
	at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.<clinit>(ClassLoaderWeavingAdaptor.java:1040)
	... 12 more
```

**Comment by Dosxx** [comment]
Could anyone help with this issue? I am running Spring boot 3.3.4 Amazon-corretto-23 aspectjweaver 1.9.22.1. Thanks in advance

**Comment by kriegaex** [comment]
This simply means that AspectJ 1.9.22.1 does not support class file versions for Java 23+, only up to Java 22.

Please note my [recent message](https://www.eclipse.org/lists/aspectj-users/msg15598.html) to the _aspectj-users_ and _aspectj-announce_ mailing lists regarding my situation as an AspectJ maintainer.

**Comment by Dosxx** [comment]
Thank you very much! I really appreciate you taking the time to respond.

**Comment by kriegaex** [comment]
The issue is valid. Why did you close it? I am reopening it.

**Comment by alex-sviatenko** [comment]
I encountered the same error while using JDK 23 and AspectJ v.1.9.22.1. Changing the JDK to v.21 fixed the issue. =)
If you prefer to use inbuilt Maven/Gradle Runners in IDE, ensure that you have selected the proper Java version in Settings.

**Comment by kriegaex** [comment]
> Changing the JDK to v.21 fixed the issue.

No, it does not. It is a workaround. What would fix the issue is an AspectJ update supporting Java 23+, hence this open issue until either I find a sponsor and am no longer on hiatus or another committer implements it.

**Comment by aclement** [comment]
AspectJ 1.9.23 with Java 23 support is out. https://github.com/eclipse-aspectj/aspectj/releases/tag/V1_9_23
